name: Chennai Flight Scraper

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
            
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
                
      - name: Install libraries
        run: pip install -r requirements.txt
              
      - name: Run Scrapers
        run: |
          python scraper_maa.py
          python scraper_bom.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/flights_data_maa.csv data/flights_data_bom.csv
          # Only commit if there are actual changes to the files
          git commit -m "Automated data fetch: Updated flight CSVs" || echo "No changes to commit"
          git push
